import 'models.dart.dart';
import 'otp.dart';

final List<Otp> mockOtpList = [
  Otp(
    id: 1,
    estateId: 101,
    propertyId: 501,
    generatedBy: 12,
    otpCode: "A9X2B1",
    barcodeData: "BARCODE_A9X2B1",
    qrCodeData: "QRCODE_A9X2B1",
    visitorName: "John Doe",
    purpose: "Guest Visit",
    validFrom: DateTime.now().subtract(const Duration(hours: 2)),
    validUntil: DateTime.now().add(const Duration(hours: 6)),
    validityHours: 8,
    status: "active",
    requiresSecurityValidation: true,
    securityClearanceLevel: "medium",
    usedAt: null,
    usedBy: null,
    metadata: {"vehicle": "Toyota Corolla", "plate": "ABJ-123-XY"},
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    updatedAt: DateTime.now(),
    timeRemaining: 6.0,
    isActive: true,
    countdownDisplay: "6h remaining",
    securityStatus: "cleared",
    destinationInfo: DestinationInfo(
      id: 900,
      name: "Main Gate",
   
    ),
    estate: Estate(
      id: 101,
      name: "Palm Estate",
  
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    property: Property(
      id: 501,
      name: "Villa 5B",
      type: "Residential",
  
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ),
  Otp(
    id: 2,
    estateId: 102,
    propertyId: 502,
    generatedBy: 15,
    otpCode: "Z7W8M3",
    barcodeData: "BARCODE_Z7W8M3",
    qrCodeData: "QRCODE_Z7W8M3",
    visitorName: "Jane Smith",
    purpose: "Family Visit",
    validFrom: DateTime.now().subtract(const Duration(hours: 1)),
    validUntil: DateTime.now().add(const Duration(hours: 5)),
    validityHours: 6,
    status: "pending",
    requiresSecurityValidation: false,
    securityClearanceLevel: "low",
    usedAt: null,
    usedBy: null,
    metadata: {"guestCount": 3},
    createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    updatedAt: DateTime.now(),
    timeRemaining: 5.0,
    isActive: true,
    countdownDisplay: "5h remaining",
    securityStatus: "awaiting",
    destinationInfo: DestinationInfo(
      id: 901,
      name: "Clubhouse",
   
    ),
    estate: Estate(
      id: 102,
      name: "Crown Estate",

      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    property: Property(
      id: 502,
      name: "Apartment 3A",
      type: "Residential",
   
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ),
  Otp(
    id: 3,
    estateId: 103,
    propertyId: 503,
    generatedBy: 20,
    otpCode: "Q2L9K8",
    barcodeData: "BARCODE_Q2L9K8",
    qrCodeData: "QRCODE_Q2L9K8",
    visitorName: "Security Team",
    purpose: "Maintenance Check",
    validFrom: DateTime.now().subtract(const Duration(hours: 3)),
    validUntil: DateTime.now().add(const Duration(hours: 9)),
    validityHours: 12,
    status: "used",
    requiresSecurityValidation: true,
    securityClearanceLevel: "high",
    usedAt: DateTime.now().subtract(const Duration(hours: 1)),
    usedBy: 99,
    metadata: {"tools": "Generator inspection kit"},
    createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    updatedAt: DateTime.now(),
    timeRemaining: 9.0,
    isActive: false,
    countdownDisplay: "Expired",
    securityStatus: "verified",
    destinationInfo: DestinationInfo(
      id: 902,
      name: "Maintenance Zone",
    
    ),
    estate: Estate(
      id: 103,
      name: "Harmony Estate",
    
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    property: Property(
      id: 503,
      name: "Block 10",
      type: "Commercial",
   
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ),
];
