// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDN09etKnt_2_p1XohbtBPmxE3Jhp48Wk',
    appId: '1:1038277350674:android:79c7e8d647609646f94fcb',
    messagingSenderId: '1038277350674',
    projectId: 'curnectgate-f9770',
    storageBucket: 'curnectgate-f9770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvWrzPP-YzjJninbgasSUsqRh9HgManzY',
    appId: '1:1038277350674:ios:de2f01033a3dc801f94fcb',
    messagingSenderId: '1038277350674',
    projectId: 'curnectgate-f9770',
    storageBucket: 'curnectgate-f9770.firebasestorage.app',
    iosBundleId: 'com.ges.curnectgate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDdfKq64UngolfA_vfpvrlmu9P4aUkrlY',
    appId: '1:1038277350674:web:f0772e4a248dc2d3f94fcb',
    messagingSenderId: '1038277350674',
    projectId: 'curnectgate-f9770',
    authDomain: 'curnectgate-f9770.firebaseapp.com',
    storageBucket: 'curnectgate-f9770.firebasestorage.app',
    measurementId: 'G-EJT8S0KD0N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvWrzPP-YzjJninbgasSUsqRh9HgManzY',
    appId: '1:1038277350674:ios:de2f01033a3dc801f94fcb',
    messagingSenderId: '1038277350674',
    projectId: 'curnectgate-f9770',
    storageBucket: 'curnectgate-f9770.firebasestorage.app',
    iosBundleId: 'com.ges.curnectgate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDdfKq64UngolfA_vfpvrlmu9P4aUkrlY',
    appId: '1:1038277350674:web:5f4ba57daae988fef94fcb',
    messagingSenderId: '1038277350674',
    projectId: 'curnectgate-f9770',
    authDomain: 'curnectgate-f9770.firebaseapp.com',
    storageBucket: 'curnectgate-f9770.firebasestorage.app',
    measurementId: 'G-CDV2CD07B6',
  );

}