import 'package:curnectgate/features/operations/OTP_Activation/model/nullSafty_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'event_requester_model.dart';

part 'event_code_model.freezed.dart';
part 'event_code_model.g.dart';

@freezed
class EventCode with _$EventCode {
  @JsonSerializable(explicitToJson: true, fieldRename: FieldRename.snake)
  const factory EventCode({
    int? id,
    String? eventCode,
    String? formattedCode,
    String? eventTitle,
    String? eventDescription,
    String? eventType,
    String? eventTypeDisplay,
    String? status,
    String? statusDisplay,
    String? statusColor,
    EventRequester? requester,
    String? address,
    String? eventLocation,
    String? eventStartDate,
    String? eventEndDate,
    String? eventStartFormatted,
    String? eventEndFormatted,
    int? expectedGuests,
    int? totalGuestsEntered,
    int? totalGuestsDenied,
    int? usageCount,
    int? guestEntryRate,
    String? qrCodeUrl,
    String? printableQrCodeUrl,
    String? specialInstructions,
    bool? isActive,
    bool? isExpired,
    bool? canBeUsed,
    bool? isOngoing,
    bool? hasEnded,
    int? daysUntilEvent,
    int? durationHours,
    String? createdAt,
    String? revocationReason,
    String? adminNotes,
    bool? isManualGeneration,
  }) = _EventCode;

  factory EventCode.fromJson(Map<String, dynamic> json) =>
      _$EventCodeFromJson(json);

  factory EventCode.fromSafeJson(Map<String, dynamic> json) {
    return EventCode(
      id: NullSafetyHelper.safeInt(json['id']),
      eventCode: NullSafetyHelper.safeString(json['event_code']),
      formattedCode: NullSafetyHelper.safeString(json['formatted_code']),
      eventTitle: NullSafetyHelper.safeString(json['event_title']),
      eventDescription: NullSafetyHelper.safeString(json['event_description']),
      eventType: NullSafetyHelper.safeString(json['event_type']),
      eventTypeDisplay: NullSafetyHelper.safeString(json['event_type_display']),
      status: NullSafetyHelper.safeString(json['status']),
      statusDisplay: NullSafetyHelper.safeString(json['status_display']),
      statusColor: NullSafetyHelper.safeString(json['status_color']),
      requester: NullSafetyHelper.safeModel(
        json['requester'],
        EventRequester.fromSafeJson,
        EventRequester.empty(),
      ),
      address: NullSafetyHelper.safeString(json['address']),
      eventLocation: NullSafetyHelper.safeString(json['event_location']),
      eventStartDate: NullSafetyHelper.safeString(json['event_start_date']),
      eventEndDate: NullSafetyHelper.safeString(json['event_end_date']),
      eventStartFormatted: NullSafetyHelper.safeString(json['event_start_formatted']),
      eventEndFormatted: NullSafetyHelper.safeString(json['event_end_formatted']),
      expectedGuests: NullSafetyHelper.safeInt(json['expected_guests']),
      totalGuestsEntered: NullSafetyHelper.safeInt(json['total_guests_entered']),
      totalGuestsDenied: NullSafetyHelper.safeInt(json['total_guests_denied']),
      usageCount: NullSafetyHelper.safeInt(json['usage_count']),
      guestEntryRate: NullSafetyHelper.safeInt(json['guest_entry_rate']),
      qrCodeUrl: NullSafetyHelper.safeString(json['qr_code_url']),
      printableQrCodeUrl: NullSafetyHelper.safeString(json['printable_qr_code_url']),
      specialInstructions: NullSafetyHelper.safeString(json['special_instructions']),
      isActive: NullSafetyHelper.safeBool(json['is_active']),
      isExpired: NullSafetyHelper.safeBool(json['is_expired']),
      canBeUsed: NullSafetyHelper.safeBool(json['can_be_used']),
      isOngoing: NullSafetyHelper.safeBool(json['is_ongoing']),
      hasEnded: NullSafetyHelper.safeBool(json['has_ended']),
      daysUntilEvent: NullSafetyHelper.safeInt(json['days_until_event']),
      durationHours: NullSafetyHelper.safeInt(json['duration_hours']),
      createdAt: NullSafetyHelper.safeString(json['created_at']),
      revocationReason: NullSafetyHelper.safeString(json['revocation_reason']),
      adminNotes: NullSafetyHelper.safeString(json['admin_notes']),
      isManualGeneration: NullSafetyHelper.safeBool(json['is_manual_generation']),
    );
  }

  factory EventCode.empty() => const EventCode(
        id: null,
        eventCode: null,
        formattedCode: null,
        eventTitle: null,
        eventDescription: null,
        eventType: null,
        eventTypeDisplay: null,
        status: null,
        statusDisplay: null,
        statusColor: null,
        requester: null,
        address: null,
        eventLocation: null,
        eventStartDate: null,
        eventEndDate: null,
        eventStartFormatted: null,
        eventEndFormatted: null,
        expectedGuests: null,
        totalGuestsEntered: null,
        totalGuestsDenied: null,
        usageCount: null,
        guestEntryRate: null,
        qrCodeUrl: null,
        printableQrCodeUrl: null,
        specialInstructions: null,
        isActive: null,
        isExpired: null,
        canBeUsed: null,
        isOngoing: null,
        hasEnded: null,
        daysUntilEvent: null,
        durationHours: null,
        createdAt: null,
        revocationReason: null,
        adminNotes: null,
        isManualGeneration: null,
      );
}
