import 'dart:convert';

import 'package:curnectgate/core/style/colors.dart';
import 'package:curnectgate/core/style/fontStyle.dart';
import 'package:curnectgate/features/member_management/onbording_prosecc/widget/app_bottom_sheet.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../../member_management/tabState/permission_tab_state.dart';

class ConfirmPermitentry extends ConsumerWidget {
  final String name;
  final String type;
  final int id;

  const ConfirmPermitentry({
    super.key,
    required this.name,
    required this.type,
    required this.id,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final extractedData = json.decode(type);
    final data = extractedData["data"] ?? {};

    final permitSummary = data["permit_summary"] ?? {};
    final permitItems = (data["permit_items"] as List?) ?? [];
    final otpGeneratedBy = data["otp_generated_by"] ?? {};

    final int permitId = data["permit_id"] ?? 0;

    final size = MediaQuery.sizeOf(context);

    return SingleChildScrollView(
      child: Column(
        children: [
          Align(
            alignment: Alignment.topRight,
            child: InkWell(
              onTap: () => Navigator.pop(context),
              child: Icon(Icons.close, color: AppColors.instance.black600),
            ),
          ),

          const SizedBox(height: 25),

          Text(
            "Confirm Permit",
            style: TextStyle(
              fontFamily: FontFamilies.interDisplay,
              color: AppColors.instance.black600,
              fontSize: 14,
              fontWeight: FontFamilies.bold,
            ),
          ),

          const SizedBox(height: 30),

          _buildUserInfoBox(
            size: size,
            visitorName: data["visitor_name"],
            generatedBy: otpGeneratedBy,
            propertyName: permitSummary["property_name"],
            unitNumber: permitSummary["unit_number"],
            items: permitItems,
            itemsCount: data["permit_items_count"],
          ),

          const SizedBox(height: 30),

          Row(
            children: [
              Expanded(
                child: _buildFeatureButton(
                  onTap: () {
                    showUserBottomSheet(
                      id: permitId,
                      context: context,
                      headertitle: data["otp_code"]?.toString() ?? "",
                      headersubtitle: data["otp_code"]?.toString() ?? "",
                      ref: ref,
                      bottom: BottomSheetView.checkoutPermitdeny,
                    );
                  },
                  title: "Deny permit",
                  color: AppColors.instance.grey500,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _buildFeatureButton(
                  onTap: () {
                    showUserBottomSheet(
                      id: permitId,
                      context: context,
                      headertitle: permitSummary["otp_code"] ?? "",
                      headersubtitle: data["otp_code"]?.toString() ?? "",
                      ref: ref,
                      bottom: BottomSheetView.checkOutPermitApproved,
                    );
                  },
                  title: "Grant permit",
                  color: AppColors.instance.black600,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildUserInfoBox({
    required Size size,
    required String? visitorName,
    required Map generatedBy,
    required String? propertyName,
    required String? unitNumber,
    required List items,
    required int? itemsCount,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 16),
      width: size.width,
      decoration: BoxDecoration(
        color: AppColors.instance.grey300,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        children: [
          _buildText(title: "Guest Name", subtitle: visitorName ?? "N/A"),
          const SizedBox(height: 20),

          _buildText(
            title: "Generated By",
            subtitle: generatedBy["name"] ?? generatedBy["email"] ?? "N/A",
          ),
          const SizedBox(height: 20),

          _buildText(
            title: "Property",
            subtitle: "$propertyName ($unitNumber)",
          ),

          if (items.isNotEmpty) ...[
            const SizedBox(height: 30),

            Text(
              "Clearance Items",
              style: TextStyle(
                fontFamily: FontFamilies.interDisplay,
                fontWeight: FontFamilies.bold,
                fontSize: 14,
                color: AppColors.instance.black600,
              ),
            ),

            const SizedBox(height: 6),

            Text(
              "${itemsCount ?? items.length} items registered",
              style: TextStyle(
                fontFamily: FontFamilies.interDisplay,
                fontSize: 12,
                fontWeight: FontFamilies.medium,
                color: AppColors.instance.teal400,
              ),
            ),

            const SizedBox(height: 15),

            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 14),
              child: Column(
                children:
                    items.map((item) {
                      return Container(
                        width: size.width,
                        padding: const EdgeInsets.all(10),
                        margin: const EdgeInsets.only(bottom: 10),
                        decoration: BoxDecoration(
                          color: AppColors.instance.grey200,
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: AppColors.instance.teal300),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              item["item_name"] ?? "Unknown Item",
                              style: TextStyle(
                                fontFamily: FontFamilies.interDisplay,
                                fontWeight: FontFamilies.bold,
                                fontSize: 13,
                                color: AppColors.instance.black600,
                              ),
                            ),
                            const SizedBox(height: 5),
                            Text(
                              item["description"] ?? "",
                              style: TextStyle(
                                fontFamily: FontFamilies.interDisplay,
                                fontSize: 11,
                                color: AppColors.instance.black400,
                              ),
                            ),
                            const SizedBox(height: 3),
                            Text(
                              item["item_category"] ?? "",
                              style: TextStyle(
                                fontFamily: FontFamilies.interDisplay,
                                fontSize: 11,
                                color: AppColors.instance.teal400,
                              ),
                            ),
                          ],
                        ),
                      );
                    }).toList(),
              ),
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildText({required String title, required String subtitle}) {
    return Column(
      children: [
        Text(
          title,
          style: TextStyle(
            fontFamily: FontFamilies.interDisplay,
            fontWeight: FontFamilies.bold,
            fontSize: 12,
            color: AppColors.instance.black300,
          ),
        ),
        SizedBox(height: 5),
        Text(
          subtitle,
          style: TextStyle(
            fontFamily: FontFamilies.interDisplay,
            fontWeight: FontFamilies.bold,

            color: AppColors.instance.black600,
          ),
        ),
      ],
    );
  }

  Widget _buildFeatureButton({
    required VoidCallback onTap,
    required String title,
    required Color color,
  }) {
    return InkWell(
      onTap: onTap,
      child: Container(
        height: 50,
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(10),
        ),
        child: Center(
          child: Text(
            title,
            style: TextStyle(
              fontFamily: FontFamilies.interDisplay,
              fontWeight: FontFamilies.bold,
              color: AppColors.instance.grey200,
            ),
          ),
        ),
      ),
    );
  }
}
